#!/usr/bin/python

"""
Magic markers
#%# family=contrib
#%# capabilities=autoconf
"""

import sys
sys.path.insert(0, '/usr/lib/mongopython')
import mongodb_commands as mongodb
import re
try:
    import json
except ImportError:
    import simplejson as json

def safe_name(unsafe_name):
    return re.sub(r"[^A-Za-z0-9_]+", "_", unsafe_name)

"""
Begin unique section.
"""

def get_server_data(timeout = 30):
    return mongodb.getServerStatus(timeout)["opLatencies"]

def print_values():
    for k, v in get_server_data().iteritems():
        if v["ops"] == 0:
            print("%s.value 0" % (safe_name(k)))
        else:
            print("%s.value %s" % (safe_name(k), float(v["latency"]) / 1000000 / v["ops"]))

def print_config_b():
    print("graph_title MongoDB operation latencies")
    print("graph_args --base 1000")
    print("graph_vlabel average latency (sec / operation)")

    for k in get_server_data():
        print("%s.label %s latency" % (safe_name(k), k[:-1]))

"""
End unique section.
"""

def print_config_a():
    print("graph_category mongodb")

def print_autoconf():
    from os import environ
    timeout = 3
    if 'autoconftimeout' in environ:
        timeout = int(environ['autoconftimeout'])
    try:
        get_server_data(timeout)
        print("yes")
    except:
        print("no (can't get mongodb opLatencies information)")

if __name__ == '__main__':
    if len(sys.argv) > 1:
        if sys.argv[1] == "config":
            print_config_a()
            print_config_b()
        elif sys.argv[1] == "autoconf":
            print_autoconf()
    else:
        print_values()
